#!/usr/bin/env bash

# ###############################################################
# PATH
# ###############################################################

# Set path -> here.
declare MPCTL="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# ###############################################################
# COMMANDS
# ###############################################################

# Developer commands:
# ... binaries
alias mpctl-dev-apply-linter='source $MPCTL/cmds/dev/apply_linter.sh'

# Infrastructure commands:
# ... local
alias mpctl-local-compile='source $MPCTL/cmds/local/compile.sh'
alias mpctl-local-compile-client='source $MPCTL/cmds/local/compile_client.sh'
alias mpctl-local-compile-key-manager='source $MPCTL/cmds/local/compile_key_manager.sh'
alias mpctl-local-compile-other='source $MPCTL/cmds/local/compile_other.sh'
alias mpctl-local-compile-server='source $MPCTL/cmds/local/compile_server.sh'
alias mpctl-local-net-setup='source $MPCTL/cmds/local/net_setup.sh'
alias mpctl-local-net-teardown='source $MPCTL/cmds/local/net_teardown.sh'
alias mpctl-local-node-activate-env='source $MPCTL/cmds/local/node_activate_env.sh'

# ... docker
alias mpctl-dkr-build-image='source $MPCTL/cmds/dkr/build_image.sh'
alias mpctl-dkr-net-down='source $MPCTL/cmds/dkr/net_down.sh'
alias mpctl-dkr-net-start='source $MPCTL/cmds/dkr/net_start.sh'
alias mpctl-dkr-net-stop='source $MPCTL/cmds/dkr/net_stop.sh'
alias mpctl-dkr-net-up='source $MPCTL/cmds/dkr/net_up.sh'
alias mpctl-dkr-net-view-status='source $MPCTL/cmds/dkr/net_start.sh'
alias mpctl-dkr-node-start='source $MPCTL/cmds/dkr/node_start.sh'
alias mpctl-dkr-node-stop='source $MPCTL/cmds/dkr/node_stop.sh'
alias mpctl-dkr-services-down='source $MPCTL/cmds/dkr/services_down.sh'
alias mpctl-dkr-services-up='source $MPCTL/cmds/dkr/services_up.sh'

# Jobs.
alias mpctl-job-pgres-dump='source $MPCTL/cmds/infra/net/pgres_dump.sh'
alias mpctl-job-pgres-restore='source $MPCTL/cmds/infra/net/pgres_restore.sh'
alias mpctl-job-pgres-truncate='source $MPCTL/cmds/infra/net/pgres_truncate.sh'
alias mpctl-job-aws-sm-rotate-keys='source $MPCTL/cmds/infra/net/rotate_keys.sh'

# Testing.
alias mpctl-testing-init-db-from-plain-text-iris-file='source $MPCTL/cmds/testing/init_db_from_plain_text_iris_file.sh'
alias mpctl-testing-init-plain-text-iris-file='source $MPCTL/cmds/testing/init_plain_text_iris_file.sh'
