#!/usr/bin/env bash

# ###############################################################
# PATH
# ###############################################################

# Set path -> here.
declare MPCTL="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# ###############################################################
# COMMANDS
# ###############################################################

# Infrastructure commands:
# ... binaries
alias mpctl-infra-bin-compile='source $MPCTL/cmds/infra/bin/compile.sh'
alias mpctl-infra-bin-compile-client='source $MPCTL/cmds/infra/bin/compile_client.sh'
alias mpctl-infra-bin-compile-key-manager='source $MPCTL/cmds/infra/bin/compile_key_manager.sh'
alias mpctl-infra-bin-compile-other='source $MPCTL/cmds/infra/bin/compile_other.sh'
alias mpctl-infra-bin-compile-server='source $MPCTL/cmds/infra/bin/compile_server.sh'

# ... docker
alias mpctl-infra-dkr-bring-down-net='source $MPCTL/cmds/infra/dkr/bring_down_net.sh'
alias mpctl-infra-dkr-bring-down-services='source $MPCTL/cmds/infra/dkr/bring_down_services.sh'
alias mpctl-infra-dkr-bring-up-net='source $MPCTL/cmds/infra/dkr/bring_up_net.sh'
alias mpctl-infra-dkr-bring-up-services='source $MPCTL/cmds/infra/dkr/bring_up_services.sh'
alias mpctl-infra-dkr-build-image-of-server='source $MPCTL/cmds/infra/dkr/build_image_of_server.sh'

# ... networks
alias mpctl-infra-net-dump-pgres-db-set='source $MPCTL/cmds/infra/net/pgres_db_dump.sh'
alias mpctl-infra-net-restore-pgres-db-set='source $MPCTL/cmds/infra/net/pgres_db_restore.sh'
alias mpctl-infra-net-rotate-keys='source $MPCTL/cmds/infra/net/rotate_keys.sh'
alias mpctl-infra-net-setup='source $MPCTL/cmds/infra/net/ctl_setup.sh'
alias mpctl-infra-net-teardown='source $MPCTL/cmds/infra/net/ctl_teardown.sh'

# ... nodes
alias mpctl-infra-node-activate-env='source $MPCTL/cmds/infra/node/activate_env.sh'
alias mpctl-infra-node-dump-pgres-db='source $MPCTL/cmds/infra/node/pgres_db_dump.sh'
alias mpctl-infra-node-restore-postgres-db='source $MPCTL/cmds/infra/node/pgres_db_restore.sh'
alias mpctl-infra-node-rotate-keys='source $MPCTL/cmds/infra/node/rotate_keys.sh'
