#!/usr/bin/env bash

# ###############################################################
# PATH
# ###############################################################

# Set path -> here.
declare MPCTL="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# ###############################################################
# COMMANDS
# ###############################################################

# Infrastructure commands:
# ... binaries
alias mpctl-infra-bin-compile='source $MPCTL/cmds/infra/bin/compile.sh'
alias mpctl-infra-bin-compile-client='source $MPCTL/cmds/infra/bin/compile_client.sh'
alias mpctl-infra-bin-compile-key-manager='source $MPCTL/cmds/infra/bin/compile_key_manager.sh'
alias mpctl-infra-bin-compile-server-cpu='source $MPCTL/cmds/infra/bin/compile_server_cpu.sh'
alias mpctl-infra-bin-compile-server-cpu-other='source $MPCTL/cmds/infra/bin/compile_server_cpu_other.sh'
alias mpctl-infra-bin-compile-server-gpu='source $MPCTL/cmds/infra/bin/compile_server_gpu.sh'
alias mpctl-infra-bin-compile-server-gpu-other='source $MPCTL/cmds/infra/bin/compile_server_gpu_other.sh'

# ... networks
alias mpctl-infra-net-setup='source $MPCTL/cmds/infra/net/ctl_setup.sh'
alias mpctl-infra-net-teardown='source $MPCTL/cmds/infra/net/ctl_teardown.sh'
